language: node_js
node_js:
  - "node"
  - 10 # use nodejs v10 LTS-
after_success:
  - git config --global user.name "chromer"
  - git config --global user.email "chuliang2013@gmail.com"
cache: npm
branches:
  only:
    - main # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public