os: linux
language: node_js
install:
  - yarn
node_js:
  - 13 # use nodejs v13 LTS-
after_success:
  - git config --global user.name "chromer"
  - git config --global user.email "chuliang2013@gmail.com"
cache: npm
branches:
  only:
    - main # build master branch only
script:
  - hexo generate # generate static files
deploy:
  strategy: git
  provider: pages
  cleanup: false
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: main
  local_dir: public